import type { ComponentType } from 'react';
import {
  ArrowTopRightOnSquareIcon,
  CheckCircleIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  XCircleIcon,
} from '@heroicons/react/24/outline';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import 'dayjs/locale/vi';
import type { Notification, NotificationType } from '../types/notification.types';

dayjs.extend(relativeTime);
dayjs.locale('vi');

type NotificationItemProps = {
  notification: Notification;
  onClick: (notification: Notification) => void;
  compact?: boolean;
};

type NotificationVisual = {
  icon: ComponentType<{ className?: string }>;
  iconClassName: string;
  label: string;
};

const VISUALS: Record<NotificationType, NotificationVisual> = {
  INFO: {
    icon: InformationCircleIcon,
    iconClassName: 'bg-blue-500/10 text-blue-600',
    label: 'Thông tin',
  },
  SUCCESS: {
    icon: CheckCircleIcon,
    iconClassName: 'bg-emerald-500/10 text-emerald-600',
    label: 'Thành công',
  },
  WARNING: {
    icon: ExclamationTriangleIcon,
    iconClassName: 'bg-amber-500/10 text-amber-600',
    label: 'Cảnh báo',
  },
  DANGER: {
    icon: XCircleIcon,
    iconClassName: 'bg-red-500/10 text-red-600',
    label: 'Cần xử lý',
  },
};

export function getNotificationDestination(targetUrl: string | null) {
  // Notifications are generated by the API. Still keep navigation internal so
  // a malformed or stale target cannot turn the notification into an external redirect.
  if (targetUrl?.startsWith('/') && !targetUrl.startsWith('//')) {
    return targetUrl;
  }
  return '/notifications';
}
export function NotificationItem({ notification, onClick, compact = false }: NotificationItemProps) {
  const visual = VISUALS[notification.type] || VISUALS.INFO;
  const Icon = visual.icon;

  return (
    <button
      type="button"
      onClick={() => onClick(notification)}
      className={`group flex w-full items-start gap-3 text-left transition-colors hover:bg-[var(--color-surface-alt)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[var(--color-primary)] ${
        compact ? 'px-3 py-3' : 'px-4 py-4'
      } ${notification.isRead ? '' : 'bg-[var(--color-primary-light)]/30'}`}
      aria-label={`${notification.isRead ? '' : 'Chưa đọc: '}${notification.title}`}
    >
      <span
        className={`mt-0.5 flex shrink-0 items-center justify-center rounded-xl ${visual.iconClassName} ${compact ? 'size-9' : 'size-10'}`}
        title={visual.label}
      >
        <Icon className={compact ? 'size-5' : 'size-5'} aria-hidden="true" />
      </span>

      <span className="min-w-0 flex-1">
        <span className="flex items-start justify-between gap-2">
          <span
            className={`min-w-0 truncate text-sm leading-5 ${
              notification.isRead
                ? 'font-medium text-[var(--color-text-secondary)]'
                : 'font-bold text-[var(--color-text-primary)]'
            }`}
          >
            {notification.title}
          </span>
          {!notification.isRead && (
            <span
              className="mt-1.5 size-2 shrink-0 rounded-full bg-[var(--color-primary)]"
              aria-label="Chưa đọc"
            />
          )}
        </span>

        <span className="mt-1 block line-clamp-2 text-sm leading-5 text-[var(--color-text-muted)]">
          {notification.message}
        </span>

        <span className="mt-2 flex items-center gap-1.5 text-xs text-[var(--color-text-muted)]">
          <span>{dayjs(notification.createdAt).fromNow()}</span>
          {notification.targetUrl && (
            <>
              <span aria-hidden="true">·</span>
              <ArrowTopRightOnSquareIcon className="size-3.5" aria-hidden="true" />
              <span className="sr-only">Có màn hình liên quan</span>
            </>
          )}
        </span>
      </span>
    </button>
  );
}
